blog/urls.py
from django.urls import path
from . import views
from django.views.decorators.http import require_POST

#app_name = 'blog'

# Index and List views of Blogs, Users, and Posts
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blog-list'),
    path('users/', views.UserListView.as_view(), name='user-list'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
]

urlpatterns += [
    path('accounts/register/', views.RegisterView.as_view(), name='register'),
]

# Detail views of Users, Blogs, and Posts
urlpatterns += [
    path('user/<int:user_pk>', views.UserDetailView.as_view(), name='user-detail'),
    path('blog/<int:blog_pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<int:blog_pk>/post/<int:post_pk>', views.PostDetailView.as_view(), name='post-detail'),
]

# Create views for Post and Blog
urlpatterns += [
    path('blogs/create', views.BlogCreateView.as_view(), name='blog-create'),
    path('posts/create', views.PostCreateView.as_view(), name='post-create'),
    path('comments/create', require_POST(views.CommentCreateView.as_view()), name='comment-create')
]

miniblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += [
    path('', include('blog.urls')),
    #path('', RedirectView.as_view(url='blog/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Blog(models.Model):
     name = models.CharField(max_length=200, help_text="Enter the name of your blog.")
     user = models.ForeignKey(User, on_delete=models.CASCADE)

class Post(models.Model):
    title = models.CharField(max_length=200, help_text="Title of the post.", blank=False)
    blog = models.ForeignKey(Blog, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    body = models.TextField()
    posted_on = models.DateField(auto_now_add=True) # Automatically set the field to now when the object is first created, cannot be edited
    last_modified = models.DateField(default=date.today)

    class Meta: 
        ordering = ['-posted_on']

class Comment(models.Model):
    text = models.TextField(help_text="Body of the comment")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    posted_on = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from blog.models import Comment

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text', 'user', 'post']
        help_texts = {
            'text': '',
        }

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.views import generic
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.forms import ModelForm

from blog.models import Blog, Post, Comment
from blog.forms import RegistrationForm, CommentForm
from django.contrib.auth.models import User

from datetime import date

class IndexView(generic.TemplateView):
    """Index view to display basic statistics of the website. Makes use of overriding the get_context_data method of superclass."""
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        """Override get_context_data() to be able to add additional items in the context dict to be available on the template"""
        context = super().get_context_data(**kwargs) # Need to call and set using parent method first

        num_blogs = Blog.objects.all().count()
        num_users = User.objects.all().count() - 1
        num_posts = Post.objects.all().count()
        try:
            latest_post = Post.objects.latest('posted_on')
        except Post.DoesNotExist:
            latest_post = None

        context.update({
            'num_blogs': num_blogs,
            'num_users': num_users,
            'num_posts': num_posts,
            'latest_post': latest_post,
            'title': 'index',
        })

        return context


class BlogListView(generic.ListView):
    """List view for displaying all the blogs."""
    model = Blog
    template_name = 'blog_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'blogs'
        })
        return context


class UserListView(generic.ListView):
    """List view of all the users."""
    model = User
    template_name = 'user_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'users'
        })
        return context

class UserDetailView(generic.DetailView):
    """Detail view for an individual user."""
    model = User
    template_name = 'user_detail.html'

    def get_object(self, **kwargs):
        self.user = get_object_or_404(User, pk=self.kwargs['user_pk'])
        return self.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': self.request.user.username,
            'blog': Blog.objects.get(user=self.user)
        })
        return context


class PostListView(generic.ListView):
    """List view of all posts across."""
    model = Post
    template_name = 'post_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'all posts'
        })
        return context


class PostDetailView(generic.DetailView):
    """Detail view for an individual post, also displays comments on the post.
    Acts as a ListCreateView for comments by displaying the CommentForm below the comments.
    Initial values for the 'user' and 'post' field in the CommentForm are set in this view using the corresponding context data
    When the form is submitted it will post to the CommentCreateView which only accepts POST requests """
    model = Post
    template_name = 'post_detail.html'

    def get_object(self, **kwargs):
        """Override get_object() method to return the correct post. Needed b/c of "view must be called with either an object pk or a slug in the urlconf" error."""
        self.post = get_object_or_404(Post, pk=self.kwargs['post_pk']) # Set post as an instance variable because it is used in get_context_data to pass the post to the CommentForm
        return self.post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initial = {
            'post': self.post,
            'user': self.request.user,
        }
        context.update({
            'form': CommentForm(initial=initial),
            'title': self.post.title,
        })
        return context

class CommentCreateView(generic.edit.FormView):
    """View used to create comments on Posts.
    Redirects to PostDetail view with list of comments"""
    form_class = CommentForm

    def form_valid(self, form):
        self.comment = form.save()
        return super().form_valid(form)

    def get_success_url(self): 
        return reverse('post-detail', kwargs={'blog_pk': self.comment.post.blog.id, 'post_pk': self.comment.post.id})



class BlogDetailView(generic.DetailView):
    """Detail view of a single blog, displays all posts ordered by their posted date."""
    model = Blog
    template_name = 'blog_detail.html'

    def get_object(self, **kwargs):
        self.blog = get_object_or_404(Blog, pk=self.kwargs['blog_pk'])
        return self.blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': self.blog.name
        })
        return context

class RegisterView(generic.edit.FormView):
    """Simple view that displays the RegistrationForm for registering to use the website."""
    form_class = RegistrationForm
    template_name = 'registration/register.html'
    #success_url = 'blog:index'

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user), 
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'register'
        })
        return context


class PostCreateView(generic.edit.CreateView):
    model = Post
    template_name = 'post_create.html'
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'create post'
        })
        return context

    def form_valid(self, form):
        self.post = form.save(commit=False)
        self.post.author = User.objects.get(id=self.request.user.id)
        self.post.blog = Blog.objects.get(user=self.request.user.id)
        self.post.posted_on = date.today()
        self.post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('post-detail', kwargs={'blog_pk': self.post.blog.id, 'post_pk': self.post.id})


class BlogCreateView(generic.edit.CreateView):
    model = Blog
    template_name = 'blog_create.html'
    fields = ['name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'create blog'
        })
        return context

    def form_valid(self, form):
        self.blog = form.save(commit=False) # Create instance of the blog, but don't save to database becuase we have to set the user which is done in the next line
        self.blog.user = self.request.user
        self.blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog-detail', kwargs={'blog_pk': self.blog.id})

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>miniblog - {{ title }} </title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width:device-width, initial-scale:1">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <nav class="sidebar">
            <ul class="sidebar-list">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'blog-list' %}">Blogs</a></li>
                <li><a href="{% url 'user-list' %}">Users</a></li>
                <li><a href="{% url 'post-list' %}">Recent Posts</a></li>
                <hr align="left" width="50%" size="1">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'user-detail' request.user.id %}">{{ request.user.username }}</a></li>
                    {% if request.user.blog_set.first %}
                    <li><a href="{% url 'blog-detail' request.user.blog_set.first.id %}">My Blog</a></li>
                    {% else %}
                    <li><a href="{% url 'blog-create' %}">Create A Blog</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'register' %}">Register</a></li>
                {% endif %}
            </ul>
        </nav>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

blog/templates/blog.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ blog.name }}</h1>
{% endblock %}

blog/templates/blog_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Create New Blog</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Blog"/>
</form>
{% endblock %}

blog/templates/blog_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ blog.name }}</h1>
    {% if user == blog.user %}
    <p><a href="{% url 'post-create' %}">create new post</a></p>
    {% endif %}
    <div class="posts">
        <ul>
            {% for post in blog.post_set.all %}
            <li><a href="{% url 'post-detail' blog_pk=post.blog.id post_pk=post.id %}">{{ post.title }}</a> - {{ post.posted_on }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Blogs</h1>
    <ul>
    {% for blog in blog_list %}
        <li><a href="{% url 'blog-detail' blog_pk=blog.id %}">{{ blog.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}


{% block content %}
    <h1>Miniblog</h1>
    <p>Lil page where you can create your own blog and post content :~)</p>
    <p>Some stats - </p>
    <ul>
        <li>Blogs -  {{ num_blogs }}</li>
        <li>Users - {{ num_users }}</li>
        <li>Posts - {{ num_posts }}</li>
        {% if latest_post %}
            <li>Latest Post - <a href="{% url 'post-detail' blog_pk=latest_post.blog.id post_pk=latest_post.id %}">{{ latest_post.title }}</a></li>
        {% endif %}
    </ul>
{% endblock %}

blog/templates/post.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p><strong>{{ post.author }}</strong> - {{ post.posted_on }}</p>
    <p>{{ post.body }}</p>

    {% if post.comment_set.all %}
        <hr>
        <p>{{ post.comment_set.all.count }} {% if post.comment_set.all.count == 1 %} Comment {% else %} Comments {% endif %}</p>
        {% for comment in post.comment_set.all %}
            <p><strong>{{ comment.user }}</strong> - {{ comment.posted_on }}</p>
            <p>{{ comment.text }}</p>
        {% endfor %}
    {% endif %}
{% endblock %}

blog/templates/post_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Create New Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create"/>
</form>
{% endblock %}

blog/templates/post_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p><strong>{{ post.author }}</strong> - {{ post.posted_on }}</p>
    <p>{{ post.body }}</p>

    {% if post.comment_set.all %}
        <hr size="1">
        <p>{{ post.comment_set.all.count }} {% if post.comment_set.all.count == 1 %} Comment {% else %} Comments {% endif %}</p>
        {% for comment in post.comment_set.all %}
            <p><strong>{{ comment.user }}</strong> - {{ comment.posted_on }}</p>
            <p>{{ comment.text }}</p>
        {% endfor %}
    {% endif %}
    <hr size="1">
    {% if user.is_authenticated %}
        <form action="{% url 'comment-create' %}" method="post">
            {% csrf_token %}
            {{ form.text }}
            {{ form.post.as_hidden }}
            {{ form.user.as_hidden }}
            <input type="submit" value="Comment" />
        </form>
    {% else %}
    <p><a href="{% url 'login' %}">Login</a> or <a href="{% url 'register' %}">register</a> to comment</p>
    {% endif %}
{% endblock %}

blog/templates/post_list.html
{% extends "base.html" %}

{% block content %}
<h1>Recent Posts</h1>
<ul>
    {% for post in post_list %}
        <li><a href="{% url 'post-detail' blog_pk=post.blog.id post_pk=post.id %}">{{ post.title }}</a> - <a href="{% url 'user-detail' post.author.id %}">{{ post.author.username }}</a> ({{ post.posted_on }})</li>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/user_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ user.username }}</h1>
<h2>Blog - <a href="{% url 'blog-detail' blog_pk=blog.id %}">{{ blog.name }}</a></h2>
<h2>Recent Posts</h2>
<ul>
    {% for post in blog.post_set.all %}
    <li><a href="{% url 'post-detail' blog_pk=blog.id post_pk=post.id %}">{{ post.title }}</a></li>
    {% endfor %}
</ul>


{% endblock %}

blog/templates/user_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Users</h1>
    <ul>
    {% for user in user_list %}
        <li><a href="{% url 'user-detail' user_pk=user.id %}">{{ user.username }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}